### ISSUE TITLE
podman pod create won't create a net namespace

### ISSUE THREAD

**Issue by bleedinge** [jcarrano/wg-podman#1]
I can't figure out an issue I'm having.

I'm setting up a pod executing this command as an user using podman 4.3.1:

`
podman pod create --name $podname --net none --infra --infra-conmon-pidfile $HOME/$podname.pid
`

`ip netns` comes back empty

The pod is created but I can't see a network namespace being set-up. Is this the right way to proceed?

Thx!

**Comment by bleedinge** [comment]
Sorry for bothering you. I think I figured it out.

A container has to be attached to the pod, then the pod will have a Pid and then you can attach the pod via its pid to the namespace (that gets created):

`sudo ip netns attach $podname $pid
`

**Comment by jcarrano** [comment]
Hi, sorry for the long delay. When you create a pod and if the pod is running, podman will create a "infra" container which runs "catatonit". The only purpose of this container is to have a pid and hold the namespace. This namespace exists but does not have a "name", that's why `ip netns` comes out empty.

The `attach` command merely creates a link to this unnamed namespace in a location that the `ip` command knows about.

So, when you say "A container has to be attached to the pod" that is true, but that is always the case even with new pods because of the "infra" container that is always created by podman.

**Comment by tobwen** [comment]
> So, when you say "A container has to be attached to the pod" that is true, but that is always the case even with new pods because of the "infra" container that is always created by podman.

Just for the notes, this behavior changed in Podman v4.2, see here:
https://github.com/containers/podman/blob/main/RELEASE_NOTES.md#changes-9

Bug report: https://github.com/containers/podman/issues/15048
PR: https://github.com/mheon/libpod/commit/c85722eb9f552f2456d33589a1417264369a6366
